version: "3"
services:
  publisher:
    build:
      context: publisher
    environment:
      - ZMQ_ADDRESS=tcp://subscriber:5555
    devices:
      - /dev/video0:/dev/video0
    command: python webcam.py
#  subscriber:
#    build:
#      context: subscriber
#    environment:
#      - DISPLAY=192.168.1.101:0
#    volumes:
#      - /tmp/.X11-unix:/tmp/.X11-unix
#    command: python subscriber.py
